### ISSUE TITLE
Tanzer chokes on HTTP POSTs longer than readsize

### ISSUE THREAD

**Issue by Pixelz** [xantronix/tanzer#2]
If a HTTP POST that is longer than readsize (defined with tanzer::server::constructor) is sent, tanzer doesn't switch to the "write" state until the remote client closes the connection.

**Comment by Pixelz** [comment]
I've come up with a "workaround", although at this point I'm not sure if this is the intended behavior or not.

Compare Content-Length from "tanzer::message::length" with the data you've read, and when it matches, reset the socket with "tanzer::session::reset write"

**Comment by xantronix** [comment]
Hi there!

Sorry for the late response; I've been on vacation lately!

If you happen to have a very small sample of code that can reproduce this problem, I'll see what I can do to make the behavior more sane, and document it accordingly.

Thanks!
