### ISSUE TITLE
Tanzer throws an error when used through SCGI

### ISSUE THREAD

**Issue by jean1** [xantronix/tanzer#3]
How to reproduce :

cd /tmp
git clone http://tanzer.io/git/tanzer.git

I copied the "scgi.tcl" from the example directory
cd tanzer
cp examples/scgi.tcl S

I added this at the begining:
lappend auto_path /tmp/tanzer/lib/

Starting the script:
./S 9000 /tmp

Then I have an Nginx  server configured in SCGI mode 

location / {
    include   scgi_params;
    scgi_pass localhost:9000;
}

Testing with "curl http://localhost" produces the following error from the script:

{can't use empty string as operand of "+"} can't use empty string as operand of "+"
    while executing
"expr {
          2
        + $headerLength
        + [string length $headerLength]}"
    (class "::tanzer::scgi::request" method "parse" line 31)
    invoked from within
"$request parse buffer"
    (class "::tanzer::session" method "handle" line 41)
    invoked from within
"$session handle $event"
    ("uplevel" body line 2)
    invoked from within
"uplevel 1 $script"
127.0.0.1  - [Wed, 04 Sep 2015 22:40:18 GMT] "-  HTTP/1.1" 500 1610 "-" "(unknown)"

**Comment by xantronix** [comment]
Hiya!

Given the fix you have so kindly contributed (so sorry for taking long to address this!), I do believe this issue is now resolved. Thank you very kindly! I've merged it.
